version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto8
  pre_build:
    commands:
    - echo "Entered the pre-build phase"
    - pwd
  build:
    commands:
    - echo "Entered build phase"
    - mvn -B package --file pom.xml
  post_build:
    commands:
    - echo "Entered the post-build phase"
    - cp /conf_scripts/location.properties /target/lavagna
    - mv /target/lavagna ./
    
artifacts:
  files:
    - /target/lavagna/**/*
