version: 0.2
phases:
  pre_build:
    commands:
    - echo "Entered the pre-build phase"
  build:
    commands:
    - echo "Entered build phase"
    - mvn -Ddatasource.dialect=MYSQL -B package --file pom.xml
  post_build:
    commands:
    - echo "Entered the post-build phase"
    - cp /conf_scripts/location.properties /target/lavagna
    - mv /target/lavagna ./
    
artifacts:
  files:
    - /target/lavagna/**/*
