version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto8
  pre_build:
    commands:
    - echo "Entered the pre-build phase"
    - pwd
  build:
    commands:
    - echo "Entered build phase"
    - mvn -B package --file pom.xml
  post_build:
    commands:
    - echo "Entered the post-build phase"
    - cp $CODEBUILD_SRC_DIR/conf_scripts/location.properties $CODEBUILD_SRC_DIR/target/lavagna
    - zip -r 9 archive.zip $CODEBUILD_SRC_DIR/target/lavagna
#    - mv /target/lavagna ./
    
artifacts:
  files:
    - $CODEBUILD_SRC_DIR/target/archive.zip
